### ISSUE TITLE
Wolf Link Pro

### ISSUE THREAD

**Issue by copystring** [qyqsoft/ISM8I#1]
Moin,

ich weiß das Modul ist für ISM8I aber ich habe ein Wolf Link Pro in dem es möglich ist wie beim ISM8I die IP-Adresse des Servers zu ändern.

Ohne zu erwarten, dass dies funktioniert versuchte ich es trotzdem. Die Verbindung kommt zu Stande. In FHEM steht Connected.
Leider stürzt FHEM kurz danach ab.

Hast du lust das Wolf Link Pro zu unterstützen? Falls ja, wie kann ich dabei helfen?

Viele Grüße

copystring

**Comment by qyqsoft** [comment]
Sry, habe kein Wolflink Pro und kenne mich damit gar nicht aus.

**Comment by copystring** [comment]
Joh. Kein ding. Habe mittlerweile https://github.com/zivillian/ism7mqtt gefunden. Das läuft super. Vielleicht hilft es jemanden anderes auch weiter.
Danke 👍
